### ISSUE TITLE
兄弟

### ISSUE THREAD

**Issue by CathayGk** [sanonz/raspberry-ip-wechat#1]
pi@raspberrypi:~/raspberry-ip-wechat $ node index.js
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'axios'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/pi/raspberry-ip-wechat/index.js:2:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
pi@raspberrypi:~/raspberry-ip-wechat $ 

测试出现这个问题。不知道怎么办了。我pi系统 就是现在树莓派官方系统

**Comment by sanonz** [comment]
在 `~/raspberry-ip-wechat` 目录执行 `npm i`
